### ISSUE TITLE
Crash when creating new Equipment

### ISSUE THREAD

**Issue by mattiasmaahl** [Brewtarget/brewtarget#634] opened 2022-02-08 12:50 UTC
So I was creating a new Equipment.

To replicate:
1. go to Equipment tab
2. right-click on the EquipmentFolder
3. select new equipment from pop-up menu
4. fill in the various details, I changed the Physics->"Mash tun Volume" and <EQUIPMENT NAME> -> Batch Size to match the boiler in mind.
5. hit save, then it crashes.

Version, Brewtarget:develop (my own local build of the latest develop)

Brewtarget-log of the crash:
[brewtarget.log](https://github.com/Brewtarget/brewtarget/files/8023877/brewtarget.log)

Here's the code that Crashes: `src/UiAmountWithUnits.cpp:158~167`

~~~
Measurement::Amount UiAmountWithUnits::toSI() {
   // It's a coding error to call this function if we are not dealing with a physical quantity
   Q_ASSERT(std::holds_alternative<Measurement::PhysicalQuantity>(this->getFieldType()));  <-- this line!
   Q_ASSERT(this->units);

   return Measurement::qStringToSI(this->getWidgetText(),
                                   this->units->getPhysicalQuantity(),
                                   this->getForcedSystemOfMeasurement(),
                                   this->getForcedRelativeScale());
}
~~~

@matty0ung you have any idea what this could be?

**Comment by matty0ung** [comment] 2022-02-08 14:22
I'll have a look either tonight or tomorrow.  If you have the stack trace that will make the root cause obvious (I hope).  If not, don't worry, as I'm sure I'll be able to reproduce on Linux.  It's probably a relatively straightforward fix.  (Famous last words.)

**Comment by mattiasmaahl** [comment] 2022-02-08 14:33
Sorry, No stacktrace available. 😞

the rows in the logfile above are the last rows in the logfile before the crash. all rows before those are from startup of the app.

**Comment by matty0ung** [comment] 2022-02-08 18:03
Had a quick look.  I think this is is because of `lineEdit_hopUtilization->toSI()` in `Equipment::save()`.  It's not meaningful because the amount is a percentage, not a measure of a physical quantity, and therefore there is no SI unit for it - hence the assert.  The fix is that, for this field, we should just use it without calling `toSI()`.  There may be one or two other fields with similar problems.  Will check and do a patch tomorrow hopefully.

**Comment by matty0ung** [comment] 2022-02-09 20:46
The short fix is in https://github.com/Brewtarget/brewtarget/pull/635.  Will have a think about something that would flush these issues out at compile-time.

**Comment by mattiasmaahl** [comment] 2022-02-10 07:04
Correct me if I'm wrong, but don't you need values stored in the variables/objects for the functions to fail? values you don't have at compile time. A test could flush out such events though? 
just my 2 cents of thoughts?! 😄

**Closed** 2022-02-10 07:58 UTC

**Comment by matty0ung** [comment] 2022-02-10 08:02
It depends. In principle at least, we know at compile time whether a field holds a percentage, a date, a density, a duration, etc.  Sometimes Qt makes it a bit harder because it doesn't play nicely with templates, but I think we can get the info from the subclass of BtLineEdit.
