### ISSUE TITLE
ABV Calculation Error

### ISSUE THREAD

**Issue by Jsakkos** [Brewtarget/brewtarget#398] opened 2018-01-28 21:46 UTC
It seems that there is an issue calculating the ABV. When I use a predefined Brewtarget recipe and "Brew it", the actual ABV doesn't match the projected ABV, even when the OG and FG are exactly as specified in the recipe. It seems possible that the projection uses the Alternate ABV formula and the actual ABV uses the standard formula. See screen shots below:
![scr1](https://user-images.githubusercontent.com/7408328/35487539-456b4462-0442-11e8-8579-360e6bcc8149.png)
![scr2](https://user-images.githubusercontent.com/7408328/35487540-457c2da4-0442-11e8-8893-b1bc931053f0.png)

**Comment by jonte** [comment] 2018-01-31 20:08
I had a look at this, and I can reproduce the same thing as you're seeing (ABV and projected ABV do not match, even when gravities are hit spot on)..

This does not seem to be an issue due to different ABV calculation formulas, but rather because the "Projected ABV" field takes the yeast attenuation in consideration. Try setting your yeast attenuation (in your recipe) to 100%, and the fields will match.

I suppose it makes sense that the ABV field gives the maximum possible ABV (based on available sugar), and and the "Projected ABV" gives the possible real-world value.

Maybe this can be better documented. I had to dig into the code to figure out what was actually going on.. :)

**Comment by pricelessbrewing** [comment] 2018-01-31 20:59
If that is the case, it seems like an error in the formulation. They should
match right?

Do we need both fields?

**Comment by jonte** [comment] 2018-02-01 08:39
@pricelessbrewing I'm not sure I understand. The calculated values should not match, since one is for ABV estimated from OG, FG and yeast attenuation, while the other ("ABV") doesn't take attenuation into account.

Maybe we should rename "ABV" -> "Fully attenuated ABV" ?

**Comment by jawsdaws** [comment] 2018-02-01 14:05
So this is the way I understand it.

For the main window ABV, the variables are the recipe's projected OG and the recipe's yeast attenuation %.

Brew notes "Projected ABV", the variables are the actual recorded OG in the postboil brew notes and the recipe's yeast attenuation %. 

Brew notes "ABV", the variables are the actual recorded OG in the postboil brew notes and the actual recorded FG in postferment in the brew notes.

**Comment by pricelessbrewing** [comment] 2018-02-03 18:49
I second tooltips, because if we don't understand what's going on, the users definitely are not. 

I would additionally suggest changing brewnotes "ABV" to something like "measured ABV".

**Comment by jonte** [comment] 2018-02-08 12:02
Re: tooltips, there are actually tooltips for these fields. They're in the lower left corner of the BrewTarget window. in PR #400 I tried to make the use of the fields a bit clearer by improving the tooltips.

**Comment by dpettersson** [comment] 2018-02-14 20:38
@rocketman768 , @mikfire  What do you think?

**Comment by rocketman768** [comment] 2018-02-15 04:05
Approved #401. Thanks for the discussion and pull requests guys :)

**Comment by dpettersson** [comment] 2018-03-24 07:59
Pullrequest merged. Closing this issue.

**Closed by dpettersson** 2018-03-24 07:59 UTC
