### ISSUE TITLE
Deleting fermentable from recipe causes a crash.

### ISSUE THREAD

**Issue by jawsdaws** [Brewtarget/brewtarget#436] opened 2018-10-15 21:42 UTC
Deleting fermentable from recipe causes a crash.  I bet this has something to do with 8cef99cb1d40e4432a9934423d1df38607a87f27

![screenshot from 2018-10-15 17-35-50](https://user-images.githubusercontent.com/3501812/46980114-9604a900-d0a1-11e8-8817-f905b6ef1f06.png)
```
Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt.
You must not let any exception whatsoever propagate through Qt code.
If that is not possible, in Qt 5 you must at least reimplement
QCoreApplication::notify() and catch all exceptions there.

```

**Comment by pricelessbrewing** [comment] 2018-10-15 22:09
#435

**Comment by jawsdaws** [comment] 2018-10-17 13:14
This doesn't have anything to do with #435 .  I haven't pulled those changes yet.

**Comment by bcbnz** [comment] 2019-01-09 23:50
Looks like this is my fault. It works fine in c93bf1f, but not in eaf3d01 which is where PR #432 was merged in. The [diff between these commits](https://github.com/Brewtarget/brewtarget/compare/c93bf1f..eaf3d01) is rather small, and I can't see anything obvious which would be causing this. Admittedly I am completely unfamiliar with the workings of the database code.

Note that the delete works for fermentables in the recipes that ship with Brewtarget. It only fails on fermentables you add, which suggests the add is failing to populate all the tables in the database.

I'm not sure how much time I'll have to dig into this. One option is to revert #432 (and reopen bug #396) until a more robust solution can be found.

**Comment by cgspeck** [comment] 2019-10-28 11:17
I was wondering if the root cause has been identified or if is any fix for this problem? 

I'm also getting the same error when I attempt to delete a fermentable from a recipe, in the console it says:

```
[21:14:49.788] ERROR : void Database::removeIngredientFromRecipe(Recipe*, BeerXMLElement*) failed to delete ingredient. DELETE FROM fermentable where id=597 FOREIGN KEY constraint failed Unable to fetch row
Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt.
You must not let any exception whatsoever propagate through Qt code.
If that is not possible, in Qt 5 you must at least reimplement
QCoreApplication::notify() and catch all exceptions there.
```

I was able to manually clean up my database by running the following script:

```sql
DELETE FROM fermentable_children WHERE child_id = 597;
DELETE FROM fermentable_in_recipe WHERE fermentable_id = 597;
DELETE FROM fermentable_in_inventory WHERE fermentable_id = 597;
DELETE FROM fermentable where id=597;
```

**Comment by mikfire** [comment] 2019-10-28 12:49
I'll look. I don't think I've seen that one but I also can't claim to have been looking.

**Comment by cgspeck** [comment] 2019-11-04 00:00
This problem has become severe for me. I triggers every time I attempt to remove a fermentable from a recipe. 

Is there anything I can do to help diagnose/fix this issue?

Is there any way I can clean or verify the integrity of my database?

**Comment by cgspeck** [comment] 2019-11-05 10:56
I had a look into this and made a change to `database.cpp` which essentially runs the SQL I mentioned above and made the application usable for me once more.

I have no idea how this actually interacts with the inventory system. If someone can review it and approve or give feedback that would be great.

**Closed** 2019-11-05 19:39 UTC
