### ISSUE TITLE
Deleting Brew-It entry

### ISSUE THREAD

**Issue by psmithazphone** [Brewtarget/brewtarget#82] opened 2015-09-15 04:22 UTC
Deleting Brew-It entry doesn't remove it from the tree list view

**Comment by theophae** [comment] 2015-09-15 08:44
Could you tell the OS and the version of Brewtarget, because it works normally in the current version.

**Comment by malavv** [comment] 2015-09-27 15:23
It doesn't in Brewtarget 2.1.0 in Windows 7 x86-64. (taken from the website)

I don't have a 2.2. installation to test though.

**Comment by rocketman768** [comment] 2015-10-04 22:44
@psmithazphone can you provide version and OS info? Will close as unreproducible otherwise.

**Comment by EvansMike** [comment] 2016-01-22 21:09
I have this too in Fedora 18 and I see: 
WARNING: deleteSelected:: unknown type 6

**Comment by rocketman768** [comment] 2016-01-24 20:59
Fixed in 8b67aa211431e9d1d574b2c5b9161f54a98e7548 just after 2.1.0 as part of the "cannot delete brewnotes" bug.

**Closed by rocketman768** 2016-01-24 20:59 UTC
