### ISSUE TITLE
Installation of new version results in duplicates of recipes and ingredients

### ISSUE THREAD

**Issue by karthil** [Brewtarget/brewtarget#896] opened 2024-11-27 04:29 UTC
The first time you launch after installing a new version, things go fine.  The second time you launch the program, you'll be prompted to upgrade/add again.  And you'll see at least one duplicate of each recipe and/or ingredient. 

![image](https://github.com/user-attachments/assets/e0b7f665-b12d-4131-9789-6035a4aec07c)
![image](https://github.com/user-attachments/assets/e6c79284-4381-43f5-92f1-be55df3d262a)

**Comment by matty0ung** [comment] 2024-11-28 00:10
Thanks for letting me know about this.  The system is supposed to skip over duplicates when it reads in new ingredients, recipes and so on, but it's obviously failing to do so.  I'll dig into what's going on and come up with a fix.

**Comment by matty0ung** [comment] 2024-11-28 15:48
I think I know what the cause of this is.  I know how to fix it, but it's a bit of work to do it cleanly.  (It's to do with when one object is owned by another -- eg a Recipe owns its "ingredient addition" records, but not its Style or equipment records.  At the moment, we do a special case for each "owned" type, and are missing some special cases.  The correct fix is to extend the work we already did on generalising ownership so that it's picked up in the XML and JSON import code.)  TLDR is I hope to have a fix in the next week to ten days.

**Comment by karthil** [comment] 2024-11-28 16:19
Thanks a bunch for the update.

**Comment by matty0ung** [comment] 2024-12-18 17:40
Hopefully this is fixed in [4.0.12](https://github.com/Brewtarget/brewtarget/releases/tag/v4.0.12).  If not, please don't hesitate to reopen this issue!

(You will see several seeming duplicates of one of the equipment profiles, but that's because they actually have a different value in pre-boil top-up (IIRC).  In the long-run we'll take this field off equipment because it's more of a recipe attribute than an equipment one.)

**Closed by matty0ung** 2024-12-18 17:40 UTC
