### ISSUE TITLE
Recipe export

### ISSUE THREAD

**Issue by tpiszcze** [Brewtarget/brewtarget#546] opened 2021-04-07 12:16 UTC
When recipes are exported with File -> Recipe -> Exports the only one currently selected recipe can be exported. Alternatively one or more recipes can be selected in recipes window and all exported to one file from menu opened with right mouse button. But then IBU calculations are missing. 
It would be great if both methods worked the same. I mean several recipes could be selected and all had IBU.

**Comment by mikfire** [comment] 2021-04-07 19:40
It is a fairly easy change to export all selected recipes from both places.

I cannot find any version of the code, going back to v2.3.0, where we exported the IBU of a recipe. I would prefer to keep it that way.

IBU is just a number. If I tell you my beer has 50 IBUs, you should probably ask me if I used Rager's, Tinseth's or Noonan's approximation. The same hops will give you slightly different values depending on the approximation you use. Without exporting the formula used, exporting the results will end poorly.

If we do export the formula, what then? If I export as Rager's and you import as Tinseth's, we will need to ignore the IBU anyway, and generate it from the %AA on the hops. It also wouldn't be terribly portable, as I have no idea what any of the other brewing software will do with that.

If you have a specific use case for this, I would be willing to think about it. But at my best reading, we haven't exported IBU on a recipe since at least v2.3.0 and I am unwilling to start.

**Comment by matty0ung** [comment] 2021-04-08 07:15
I think if we were going to export `IBU` then we would have, as Mik says, to export `IBU_METHOD` as well.  Both are "extensions" in the BeerXML standard, which means they're optional fields and not required for the file to be valid.  (We currently ignore them in import if they are present, preferring to calculate a value ourselves.)

@tpiszcze Could you tell us what you're doing with the exported files - eg which other program you're importing them to?  It would help us understand the best approach here.

**Comment by tpiszcze** [comment] 2021-04-08 12:33
I just export it as html only to share with other homebrew freaks. 
I found it handy to have more recipes in one export (eg to provide with batch of several "samples" to try). 
It would be also nice to have what method was used to estimate IBU.   :)

**Comment by matty0ung** [comment] 2021-04-10 07:18
OK, I see, makes sense.

There's some work we want to do to refactor the XML export (to reuse the new code that does import).  When we get to that, we could consider adding IBU and IBU_METHOD as "export only" fields, ie things we write out to the XML but don't bother reading in (because, as Mik says, it's better for us to calculate it).

**Comment by tpiszcze** [comment] 2021-04-13 09:48
I just export it as html only to share with other homebrew freaks. 
I found it handy to have more recipes in one export (eg to provide with batch of several "samples" to try). 
It would be also nice to have what method was used to estimate IBU.   :)

**Comment by tpiszcze** [comment] 2021-04-13 15:19
Sorry guys. I looked again at export recipe methods and found that the IBU is missing only when selected more that one recipe. Also when there is only one recipe exported beside IBU value there is calculation method too. 
So it would be nice just to have option to export multiple recipes in one html file with non-zero IBU value.

**Comment by matty0ung** [comment] 2021-04-13 16:29
I just had a quick go now.  When I tried (on the most recent code), the difference in whether IBU is included seems to depend not on how many recipes I'm exporting, but whether I export them to XML or HTML.  Seemed to be excluded in XML and included in HTML.  That said, I didn't test a lot of different permutations.

@tpiszcze You said you were exporting to HTML, is that right?  Also, what version of the software are you running?

**Comment by tpiszcze** [comment] 2021-04-14 23:59
Yes, I use it only for HTML export. 
Well, I have to apologize you a bit. 
The version I used was compiled on Feb 8. The files in zip archive are dated Jan 28. All newer versions did not compile.  I thought it was because of qt-5.12. On my other machine with qt-5.15 it compiled.
Today I got current zip and to my surprise it did compile. All IBUs are present in multiple recipes html file. But I cannot check it on my database. I tried to merge it or restore.  Merge seems have no effect at all. When restored brewtarget ends with error:
The application encountered a fatal error.
Error message:
SELECT id FROM  No query Unable to fetch row
And in CLI there is message:
[01:45:42.889] ERROR : void Database::populateElements(QHash<int, T*>&, Brewtarget::DBTable) [with T = BrewNote] SELECT id FROM  No query Unable to fetch row
When new (today compiled) BT was started with old DB it asked me for password (?!). I had to remove sqlite file to start it.

**Comment by mikfire** [comment] 2021-04-15 01:48
Well. That was one fix.

If brewtarget is prompting for a password on startup, it means it thinks you want to use a postgresql database, not a sqlite database.

Easiest way to figure that out is to open your config file (~/.config/brewtarget/brewtarget.conf, maybe ~/.config/brewtarget/brewtarget-debug.conf) and find two parameters: config_version and dbType. If config_version is set to 1 and dbType is set 1, then we will use SQLite. If config_version is set to 1 and dbType is set to 2, then we will use postgresql. 

Should you run into this problem again, just close all your brewtargets, edit the config file and set dbType to the proper value.

Why this happened is a little harder. In slightly older version of brewtarget, there was no config_version. In that case, either having no dbType present or having a dbType of 0 meant SQLite and dbType 1 meant postgres. I have code in place that is supposed to handle either setting the dbType if it isn't present or incrementing the dbType by one if the config_version isn't present and then setting the config_version.

I am not quite sure what happened in your case. If you happen to have an older brewtarget.conf file laying around, it would be helpful to see it. My guess is that your dbType got double incremented somehow, but I am not coming up with a brilliant idea as to how. Every test I can think to run on that part of the code seems to be behaving.

**Comment by mikfire** [comment] 2021-04-15 04:03
Yeah. Ignore that last bit. 

I was able to recreate I think what you are seeing, and I am concerned that you may be mixing and matching brewtarget versions and databases.

I can reproduce the prompt to login problem by running a stock brewtarget 2.4.0, running something out of dev and then running the stock 2.4.0 version again. The config file in the develop branch is different from the release 2.4.0 config file, as I explained previously. In stock 2.4.0, dbType = 1 means postgres and we need a password. In develop-brewtarget, dbType = 1 means sqlite.

I can also recreate the core dump by running a stock 2.4.0 brewtarget with a recent default-db.sqlite in share/brewtarget. The dump looks like:
```bash
[00:00:38.452] WARNING : Log is in a temporary directory: /tmp/brewtarget_log.txt
[00:00:38.453] ERROR : Data directory "/home/mik/.config/brewtarget" is missing.  Some features will be unavaliable.
[00:00:39.948] ERROR : void Database::populateElements(QHash<int, T*>&, Brewtarget::DBTable) [with T = BrewNote] SELECT id FROM  No query Unable to fetch row
terminate called after throwing an instance of 'QString'
```
The schema is significantly changed in recent weeks in the develop branch. I do not think we can mix and match them any longer.

**Comment by beren12** [comment] 2021-09-13 23:27
> dbType = 1

Ohhh, using numbers to define things and changing the meaning of them? Would it be possible to use strings and parse it to what it needs to be instead? It's far safer to do it that way as this issue also shows. Normally numbers in an enum would never change meaning there would just be new numbers for new things.

**Comment by matty0ung** [comment] 2021-09-14 06:49
> > dbType = 1
> 
> Ohhh, using numbers to define things and changing the meaning of them? Would it be possible to use strings and parse it to what it needs to be instead? It's far safer to do it that way as this issue also shows. Normally numbers in an enum would never change meaning there would just be new numbers for new things.

I'm not sure what line of code you're referring to.  Yes, generally, we do want to store enums as strings in the DB and in config files etc (though I'm less worried about writing the value of an enum out to a log file as a number because that's just a bit of transient diagnostic).  There are various TODO comments in the code marking some of the places where we still need to do this.  It's mostly lack of bandwidth rather than lack of desire that means it hasn't happened yet.  If you want to have a stab at making some of the changes then we'd welcome your PR -- though I suggest for anything to do with the DB that you wait until @mikfire has approved https://github.com/Brewtarget/brewtarget/pull/617 as there are some significant changes there.

**Comment by matty0ung** [comment] 2022-09-25 07:33
I now see what you mean about `dbType = 1`.  It's in the config/saved settings file.  I agree it's a bit horrible because you have to look at the source code to know what 1 means in this context.  One day it would be nice to fix all of this and maybe even use a nicer config file format such as TOML.  (Currently we use Qt default.)

**Comment by matty0ung** [comment] 2023-04-30 10:37
We've changed the way exporting to HTML works since this ticket was raised.  @mattiasmaahl made a neat print preview dialog that can print and output to PDF and HTML.

We don't currently support printing multiple recipes, and that means, if you want export to HTML, you need to do it one recipe at a time.  AFAICT however, we do include the correct IBU info in the printout / HTML output. 

I'm going to close this issue since the IBU thing is working-as-designed.  If outputting/exporting multiple recipes at a time to HTML is still something you want to do, please don't hesitate to open a new issue specifically about that.

**Closed by matty0ung** 2023-04-30 10:37 UTC
