### ISSUE TITLE
Hops inventory does not update

### ISSUE THREAD

**Issue by tpiszcze** [Brewtarget/brewtarget#324] opened 2016-09-28 09:09 UTC
BT 2.4.0, Slackware 14.2, sqlite.
I am trying to update inventory field value but it is not saved to database.  It is the same with hops, fermentables and misc. Is there other way to change it (besides tables edit with external tool)?

**Comment by mikfire** [comment] 2016-09-28 13:16
I think this is a known issue
(https://github.com/Brewtarget/brewtarget/issues/315)

It has been fixed, but I have been really busy with life and may not
have merged everything around properly.

Try the stable/2.4.0 branch and see if the problem is resolved.
Fixing anything that has broken will require editing the database
tables directly.

Mik

--
  Mik Firestone
  mikfire@fastmail.com



On Wed, Sep 28, 2016, at 05:09, tpiszcze wrote:
> BT 2.4.0, Slackware 14.2, sqlite.
>  I am trying to update inventory field value but it is not saved to
>  database.  It is the same with hops, fermentables and misc. Is there
>  other way to change it (besides tables edit with external tool)?
> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].
>


Links:

  1. https://github.com/Brewtarget/brewtarget/issues/324

**Comment by tpiszcze** [comment] 2016-09-28 14:00
Right. I downloaded current git and now it works good. Thanks. 
My fault I searched for issues with inventory problems but only that have "open" status...

**Comment by dpettersson** [comment] 2016-10-10 16:29
Maybe we should close this issue since it isn't an issue anymore. :)

**Comment by mikfire** [comment] 2016-10-15 16:45
Closed as duplicate :)

**Closed by mikfire** 2016-10-15 16:45 UTC
Labels: duplicate
