### ISSUE TITLE
Hangs on update check

### ISSUE THREAD

**Issue by jeroen79** [Brewtarget/brewtarget#906] opened 2024-12-19 15:41 UTC
Tried opening verison 4.0.10 but it hangs on updatecheck

![image](https://github.com/user-attachments/assets/0632f10e-6160-42e4-a83c-e046b1d94484)

[16:39:28.438] (ar8) INFO : void LatestReleaseFinder::checkMainRespository() Sending request to  "https://api.github.com:443/repos/Brewtarget/brewtarget/releases/latest" to check for latest release  [LatestReleaseFinder.cpp:77]
[16:39:28.746] (ar8) INFO : void LatestReleaseFinder::checkMainRespository() Latest release is "4.0.12" (parsed as QVersionNumber(4.0.12) )  [LatestReleaseFinder.cpp:146]
[16:39:28.747] (ar8) INFO : void {anonymous}::checkAgainstLatestRelease(QVersionNumber) Latest release is "4.0.12" ) ; currently running 4.0.10 (parsed as "4.0.10" )  [Application.cpp:214]
[16:39:28.748] (ar8) WARNING : QObject::setParent: Cannot set parent, new parent is in a different thread  [:0]

Might also be nice if updatecheck could be disabled in options.

**Comment by matty0ung** [comment] 2024-12-19 15:48
Yes, sorry, there's a bug in 4.0.10 about the update check (see https://github.com/Brewtarget/brewtarget/issues/878).   It's fixed in 4.0.11.  (Apologies for the irony of telling you that the fix for the bug in "check for update" is to do an update.)

This is normally a relatively stable bit of the code, but the root cause of the bug was changes we had to make as part of migrating from Qt5 to Qt6.  So, hopefully, a one-off issue.

Normally, if you don't want to update, you can just say "Don't remind me", which turns off the reminder until until the next new release.  But I'll have a look at putting something in the options that allows you to say "Never remind me about new releases".

**Closed as completed** 2024-12-19 15:49 UTC
