### ISSUE TITLE
Use Brewerwall ingredient data

### ISSUE THREAD

**Issue by rocketman768** [Brewtarget/brewtarget#290] opened 2016-06-27 01:29 UTC
From @mikfire's previous comment:

> So why don't we just pull this all from brewerwall?

[Brewerwall](https://github.com/brewerwall)

I think it is a great idea to always be up-to-date with the latest ingredients if the maintainer really puts effort into it. To bootstrap, we would need a mapping between his ids and ours for ingredients we already have, or we can mark all our existing database entries as deleted.

**Comment by pricelessbrewing** [comment] 2017-04-28 00:20
I'm not sure this is being maintained anymore, since he never responded to your comment on his repo. 

Does anyone know of a similar database for malts?

**Comment by mikfire** [comment] 2017-05-01 21:17
In my perfect world, such a database would be maintained by a neutral third party and allow submissions (with something like a git pull request so that they can be curated) for updates. Additionally, each ingredient would be assigned a unique ID (like a UUID) so that the ingredients would be portable over all the brewing software.

That is also the world where the AHA maintains the beerXML specification, since they are a neutral third party. It is also the world where I am rich.

**Comment by pricelessbrewing** [comment] 2017-05-02 00:17
Sounds like a nice place. 

I've been considering making making such a database of ingredients with files in JSON, xml, and csv in a BeerXML 1.0 format as well as an extension of it for more ingredient specs that aren't currently part of the beerxml format.  When importing, my software would first check for a matching entry in the extended database, if not it would use the BeerXML 1.0 standard format entry. Should be able to add your sql format as well

Is that something you would be interested in using?

**Comment by dmofot** [comment] 2017-05-09 15:37
I think the issue is more that @griffithben doesn't always get notifications from [brewerwall](https://github.com/brewerwall).  We have a homebrew slack that he is pretty active on, so I'll ping him there.

**Comment by pricelessbrewing** [comment] 2018-08-15 00:59
@griffithben Any intention of adding other ingredients to brewerwall? Grains in particular? 

I think moving to their yeast database, or at least maping their attenuation min-max to the brewtarget database, then filling in the rest of the blanks (if they exist) manually, would be great. Would necessitate a change in the FG formula, and should account for mash temperature as well in accordance with #410  and #344

**Comment by matty0ung** [comment] 2024-06-10 20:04
I have added the brewerall yeast data to our default content as part of https://github.com/Brewtarget/brewtarget/pull/799.

**Closed by matty0ung** 2024-06-10 20:04 UTC
Labels: enhancement
