### ISSUE TITLE
Database errors

### ISSUE THREAD

**Issue by jimdbr** [Brewtarget/brewtarget#801] opened 2024-07-30 01:25 UTC
Latest version, pulled today and built on Linux Mint:

ERROR
Unable to import some or all of new default data
Error reading settings from DB
Log file may contain more details

[brewtarget.log](https://github.com/user-attachments/files/16420643/brewtarget.log)

**Comment by matty0ung** [comment] 2024-07-30 02:56
Thanks for uploading the log.  I can see what the problem is.  Will have a fix for you to try soon.

**Comment by matty0ung** [comment] 2024-07-30 03:23
When you get a chance, could you let me know if https://github.com/Brewtarget/brewtarget/pull/802 fixes things for you?

**Comment by jimdbr** [comment] 2024-07-30 13:51
Pulled and built this morning. Still seeing errors.
[brewtarget.log](https://github.com/user-attachments/files/16428989/brewtarget.log)

**Comment by matty0ung** [comment] 2024-07-30 14:29
Ah, sorry, on rereading it, I realise what I wrote was very ambiguous!

Are you able to apply the code changes in https://github.com/Brewtarget/brewtarget/pull/802/files to your local codebase and compile and run that?  (I didn't yet commit https://github.com/Brewtarget/brewtarget/pull/802 to what gets built overnight, because I thought I'd wait and see if it fixed things for you or just uncovered other errors!)

**Comment by jimdbr** [comment] 2024-07-30 14:59
OK. Operator error on my part. I will try to apply the changes tonight and see what happens.

**Comment by matty0ung** [comment] 2024-07-30 16:04
Brilliant - thanks!  This is different errors, so it's progress!  I'll take a look.

**Comment by matty0ung** [comment] 2024-07-30 19:14
I've merged another fix into the main branch.  That _should_ fix the most recent error in `brewtarget-save.log`.  But if you could try it and let me know what happens, that would be great.

Additionally, if you have an earlier version of your database (pre the upgrade to v 11) that would also be good to try.  (There should have been a back-up saved in the same directory called something like `2024-06-03 16∶06∶10 database.sqlite backup (before upgrade from v9 to v11)`.  I _think_ your DB got upgraded to 11 when there was still a bug in the code, which is why you're getting the `Could not read default_content column from settings table` error just after start-up and thus not getting the new content from https://github.com/Brewtarget/brewtarget/blob/develop/data/DefaultContent002-BJCP_2021_Styles.json, https://github.com/Brewtarget/brewtarget/blob/develop/data/DefaultContent003-Ingredients-Hops-Yeasts.json and https://github.com/Brewtarget/brewtarget/blob/develop/data/DefaultContent004-MoreYeasts.json

**Comment by jimdbr** [comment] 2024-07-30 19:55
Thanks for all the hard work. This is getting much better.

Pulled, rebuilt and set my database back to version 10. First attempt failed because DefaultContect004-MoreYeasts.json was not installed in /usr/local/share/brewtarget. After I downloaded the file, brewtarget converted my database and added the new ingredients. Brewtarget starts and runs with one lingering error:

ERROR : double Recipe::ibuFromHopAddition(const RecipeAdditionHop&) Using Hop volume as weight - THIS IS PROBABLY WRONG!

Log file attached.

[brewtarget.log](https://github.com/user-attachments/files/16432832/brewtarget.log)

**Comment by matty0ung** [comment] 2024-07-31 06:48
Brilliant.  For the moment, you can safely ignore that particular error.  (I'll do a patch to fix it.)  It's logging when it shouldn't (because I missed a `!` character in the `if` condition, D'oh!).  In future, if you use liquid hop extracts etc, you'll see that error logged because we don't yet have the correct formulae for obtaining IBU from volume-measured hop additions.

**Comment by jimdbr** [comment] 2024-07-31 15:15
Thanks again. It looks like my recipes survived the database upgrade so all is good here.

**Closed** 2024-07-31 19:40 UTC
