### ISSUE TITLE
Saving error

### ISSUE THREAD

**Issue by xboxc** [Brewtarget/brewtarget#373] opened 2017-07-07 16:06 UTC
This is for Brewtarget 2.3.0 on Mac platform.
When I close program and open again, all my saved recipes and other items it's gone.
The program  looks like I open it first time.

**Comment by dpettersson** [comment] 2017-09-23 08:55
Does it say anything if you open in from the command line?

**Comment by xboxc** [comment] 2017-10-01 15:48
I don't know. I only open it from icon.

**Comment by xboxc** [comment] 2017-10-01 15:50
No no. If i create backup and use a restore from backup option and reset program, then all recipes is in program normally. 
I must every time use this option.

**Comment by badcrc** [comment] 2017-11-03 12:36
This happened to me log ago (I moved to a web-based software) and was when the program asked if you want to save the changes, if you select no (even without making any changes) it deleted the database. 

I had my database on my Dropbox folder if that helps.

**Comment by pricelessbrewing** [comment] 2018-08-15 02:07
Looks like we're having quite a few database issues on mac build. If there are any devs available to do thorough testing on a mac build to try and reproduce these errors on 2.3 first, then against dev build to find out if it's been fixed or if it needs to be fixed before release. #333

**Comment by JulianVolodia** [comment] 2020-02-03 03:07
Hi @pricelessbrewing 

Could you reference that other bugs?

Hi @xboxc have you any additional info. Like MacOS version and some any logging output for investigation. Are you using Brewtarget still?

**Comment by matty0ung** [comment] 2021-09-06 04:27
I believe this is resolved in various other fixes. Please re-open if not.

**Closed by matty0ung** 2021-09-06 04:27 UTC
Labels: bug
