### ISSUE TITLE
Problems with OGs and FGs for each style (2.3.0)

### ISSUE THREAD

**Issue by JAUCBN** [Brewtarget/brewtarget#166] opened 2016-02-03 20:01 UTC
I installed the Linux 64-bit version of the 2.3.0, and I'm facing some problems with the OGs and FGs for each style. They are appearing with dots and commas mixed, and higher values. 
For example: Belgian Golden Strong Ale
OG min: 1,070 sg
OG max: 1.095,000 sg
FG min: 1.050,000 sg
FG max: 1.016,000 sg

Do you know what's wrong?

Thanks

**Comment by rocketman768** [comment] 2016-02-05 04:39
Have you noticed this issue anywhere else?

@renato, do you see this issue? Wondering if it is related to #65

**Comment by JAUCBN** [comment] 2016-02-05 12:40
I noticed the same issue in the Volume of the Mash Tun

378.541.178,000 L

**Comment by danielm5** [comment] 2016-02-09 01:05
In Spanish we write the numbers with format: ',' is a decimal separator and '.' is a thousand separator.

**Comment by mikfire** [comment] 2016-04-27 02:07
Is this still an issue? I will take yet another swing at the internationalization stuff if I need to.

**Comment by JAUCBN** [comment] 2016-05-06 18:06
Unfortunately, is still an issue here. I have updated to the Version 2.3.1.1 and still have the same problem

**Comment by mikfire** [comment] 2016-05-06 23:50
OK. I will see if i can fix it. Thanks.

**Comment by mikfire** [comment] 2016-05-07 14:07
I've tried a few branches (2.3, 2.3.1 and HEAD) and I cannot reproduce the problem.
![Shot from v2.3.1](https://dl.dropboxusercontent.com/u/25337777/screens/shot-2016-05-07_09-59-42.jpg)

So I need more information, please. What distro, what version of Qt and can you also show me the output from the locale command?

**Comment by JAUCBN** [comment] 2016-05-09 12:54
Hi, I'm using Ubuntu 14.04 LTS, Qt 5.2.1, and here is the output
![bt_ogfg_issue](https://cloud.githubusercontent.com/assets/17052835/15113667/0d379e6c-15cc-11e6-964d-9f73129bd308.jpg)

**Comment by mikfire** [comment] 2016-05-09 21:41
What is your locale set to? This looks like brewtarget thinks you are in a
locale that uses . as the thousands separator and , as the decimal point.
I'm assuming you are not, otherwise you wouldn't have opened the bug.

Mik

Hi, I'm using Ubuntu 14.04 LTS, Qt 5.2.1, and here is the output
[image: bt_ogfg_issue]
<https://cloud.githubusercontent.com/assets/17052835/15113667/0d379e6c-15cc-11e6-964d-9f73129bd308.jpg>

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub
<https://github.com/Brewtarget/brewtarget/issues/166#issuecomment-217856190>

**Comment by JAUCBN** [comment] 2016-05-09 22:04
I'm in Brazil, and here we use the "." as thousand separator, and "," as decimal point. But on the older version of BT 2.1.0, this problem doesn't appear. I didn't change anything after the upgrade to 2.3.1. Sorry, if its something obvious but I thought that it wouldn't change from one to another. Where can I change the locale?

**Comment by renato** [comment] 2016-05-10 02:39
@rocketman768 Sorry, I just saw the mention today.

I wasn't using Brewtarget for a while but I compiled it today (from "develop" branch).

I think there something odd indeed, but it's not everywhere. My mash tun volume is fine (32 L), and for example the American Amber Ale has the right statistics (OG 1,045 - 1,060; FG 1,010 - 1015), but some other styles have wrong data:
American Barleywine - min FG 1.016,000
American IPA - FG 1.056,000 - 1.075,000; OG 1,010 sg - 1.018,000 sg

It is really mixed, as described. I'm using the "develop" branch and I'll take a further look tomorrow.

@JAUCBN You can test setting `LC_NUMERIC` to `en_US.UTF-8` (`LC_NUMERIC=en_US.UTF-8 brewtarget`)

BTW, the issue doesn't happen using `en_US` in `LC_NUMERIC`.

**Comment by JAUCBN** [comment] 2016-05-12 20:17
@renato I tried opening with `en_US.UTF-8` and it really worked. 

Thanks for the help, also to @rocketman768  and @mikfire , and sorry to bother.

**Comment by mikfire** [comment] 2016-05-12 21:06
Thank you very much for reporting the bug. I will fix it, and I am glad you
have a work around.

Mik

**Comment by mikfire** [comment] 2016-06-01 01:27
The fun part about this is that brewtarget doesn't do any anything with respect to internationalization. Anything to do with displaying the numbers properly for the specific locale is left to Qt.

I will investigate more, but I am not really sure this is our problem. It may be something weird in Qt.

**Comment by castreixanas** [comment] 2016-11-13 02:22
Hello.
Have a bug with OG and FG ranges.

See yelow in image, OG for this style don't have min and max range. In FG have min range, but don't have max range.
In style editor OG min range mask is x.xxx,xxx sg and max range x,xxx sg. FG is min x,xxx sg and max range x.xxx,xxx sg.
I change to x,xxx format, but I can't save.

Have S.I. units, and 20/20 C S.G. configured.


![captura](https://cloud.githubusercontent.com/assets/23426734/20243207/3387383c-a94e-11e6-8ddd-78d0b1e9847d.JPG)

**Comment by mikfire** [comment] 2016-11-13 03:39
Out of curiosity, what is your LANG environmental variable set to?

Mik

--
  Mik Firestone
  mikfire@fastmail.com



On Sat, Nov 12, 2016, at 21:22, castreixanas wrote:
> Hello.
>  Have a bug with OG and FG ranges.
> See yelow in image, OG for this style don't have min and max range. In
> FG have min range, but don't have max range.
>  In style editor OG min range mask is x.xxx,xxx sg and max range x,xxx
>  sg. FG is min x,xxx sg and max range x.xxx,xxx sg.
>  I change to x,xxx format, but I can't save.
> Have S.I. units, and 20/20 C S.G. configured.
> captura
> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[1], or mute the thread[2].
>


Links:

  1. https://github.com/Brewtarget/brewtarget/issues/166#issuecomment-260162215

**Comment by castreixanas** [comment] 2016-11-13 14:51
hello, my system complete report you can view in this url:

http://speccy.piriform.com/results/5DX4gOTQLInkBE7FV84uewZ

lang is spanish es-es, spain international alphabet.

If you want, I can test in my system your arrangements.

2016-11-13 4:39 GMT+01:00 mikfire <notifications@github.com>:

**Comment by castreixanas** [comment] 2016-12-08 01:00
Hi.
I discovered the problem.

When windows in the regional configuration is configured in "spanish united
states (es_us)", brewtarget works fine.
When configured "Spanish Spain (es_es)", brewtarget does not work well.

The point is that in the USA the thousands separator is "," and the decimal
separator is "."
While in Spain (and throughout Europe, except UK) the thousands separator
is "." And the decimal separator is ","

So brewtarget gets into a mess by transforming the data, and most fields
parse it wrong.

Please be grateful if it is possible to launch an urgent patch for this
problem, as it becomes quite difficult to use the program under these
conditions. (And probably this problem is currently replicating in all
users of the metric system, which is the majority of countries in the
world).

Thank you.

2016-11-13 4:39 GMT+01:00 mikfire <notifications@github.com>:

**Comment by malavv** [comment] 2017-01-10 19:05
@mikfire, do we know if this is still an issue?

**Comment by mikfire** [comment] 2017-01-10 21:45
It is. I think I have half a clue as to what is happening. It isn't
still the full story, because I cannot explain why it happens only in
some fields, not all.


This is what is happening.
 1. The default database is built using en_US.utf8 encoding;
 2. This causes things like the OG min/max to be written using numbers
    like 1.010 or 1.045 -- en_US decimal separator, so this would be
    1,010 or 1,045 in pt_BR;
 3. We read these numbers from the database. The nature of this call
    translates the double into a QVariant and then into a QString that
    looks like "1.010" or "1.045";
 4. We call Brewtarget::toDouble(), which gets the system Locale and
    calls QLocale::toDouble(). Well, in a pt_BR locale, "1.045" gets
    converted into 10^3 + 45 or (as we would write it in en_US 1,045).
I guess we should be treating the encoding like we do SI -- everything
gets stored in a known encoding and then we leave it until the very,
very end to display in the current locale.


The really hard part is how to fix what is already broken. For that, I
would need to look at a broken database and see what values are being
stored and come up with a plan for fixing.


Mik

--

  Mik Firestone

  mikfire@fastmail.com







On Tue, Jan 10, 2017, at 14:05, Maxime Lavigne (malavv) wrote:

> @mikfire[1], do we know if this is still an issue?



> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[2], or mute the thread[3].
> 




Links:

  1. https://github.com/mikfire
  2. https://github.com/Brewtarget/brewtarget/issues/166#issuecomment-271666582

**Comment by mikfire** [comment] 2017-01-10 22:51
Actually, I think I have an astonishingly easy fix. It's a little brute force.

The reason it only happened in some fields was that I was using slightly different methods. Most places invoked BtLineEdit::setText(double amount, int precision). StyleEditor was using a small bit of syntax sugar I created and called BtLineEdit::setText(BeerXMLElement *element). 

As long as I force things to use the first call instead of the second, the gravities are displayed correctly as it will never go through the conversions. I still need to think about this and make some tests to verify the solution is this relatively straight forward. I will also likely need to break my database a bit.

I may get a solution checked in tonight.

**Comment by mikfire** [comment] 2017-01-12 03:37
I really would like to believe pull request #336 fixes this. If somebody in the afflicted region could test the branch and see if it works, I would be grateful.

**Comment by castreixanas** [comment] 2017-01-13 21:14
@mikfire 

Hi. I can do the test. But I need a compiled version for windows, and I do not know where to download it.

Or teach me another way I can do the test.

I am waiting for the information or the download link.

Greetings.

**Closed** 2017-01-27 14:28 UTC
Labels: bug, high priority
