### ISSUE TITLE
"Brew it" crashes Mac app

### ISSUE THREAD

**Issue by 95ep** [Brewtarget/brewtarget#747] opened 2023-05-01 14:18 UTC
Was a bit quick to say that the latest Mac build works, seems like there still are some problems with the Mac build unfortunately

Whenever I hit the "Brew it" option for a recipe the app crashes, see screenshot. The log message seems rather generic.
```
[16:16:03.000] (3yz8k1s) WARNING : Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt.
You must not let any exception whatsoever propagate through Qt code.
If that is not possible, in Qt 5 you must at least reimplement
QCoreApplication::notify() and catch all exceptions there.
  [:0]
```

<img width="927" alt="Screenshot 2023-05-01 at 16 16 24" src="https://user-images.githubusercontent.com/35732139/235465539-9b99d9f1-fec6-4155-bec3-7a956ca59325.png">

**Comment by matty0ung** [comment] 2023-05-01 14:31
Will investigate.  From a quick look, the "good" news is that I can reproduce this on Linux.

**Comment by matty0ung** [comment] 2023-05-02 03:35
This is because I left some old code in the "digit widget" class when I refactored the "display amounts" code.  I have a fix working locally.  Will do a PR for that and for https://github.com/Brewtarget/brewtarget/issues/748.

**Comment by matty0ung** [comment] 2023-05-15 06:22
Should be fixed in https://github.com/Brewtarget/brewtarget/releases/tag/v3.0.9.  Please re-open if not!

**Closed by matty0ung** 2023-05-15 06:22 UTC
